version: 2.1

jobs:
  echo:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Greet
          command: echo "I love ${COLOR} builds."
          environment:
            COLOR: "green"

workflows:
  main:
    # never run
    when: false
    jobs:
      - echo
